# Generated by Django 4.0.4 on 2022-05-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updates',
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
