# Generated by Django 4.0.4 on 2022-05-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_remove_room_description_remove_room_updates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='size',
            new_name='price',
        ),
    ]
