# Generated by Django 4.0.4 on 2022-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0006_stade_room_session_room_stade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Session',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
