# Generated by Django 4.0.4 on 2022-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0010_payment_remove_room_classe_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Session',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
