# Generated by Django 4.0.4 on 2022-05-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0011_alter_room_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('dof', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
