# Generated by Django 4.0.4 on 2022-05-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0012_coor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='coor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stud.coor'),
        ),
    ]
