# Generated by Django 4.0.4 on 2022-05-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0013_ticket_coor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='room',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stud.ticket'),
        ),
    ]
