# Generated by Django 4.0.4 on 2022-05-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0014_remove_ticket_ticket_room_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment',
        ),
    ]
