# Generated by Django 4.0.4 on 2022-05-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0015_remove_ticket_classe_remove_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stud.coor'),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
