# Generated by Django 3.2.13 on 2022-05-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0016_alter_room_ticket_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ticket',
        ),
    ]
